version: "3"
services:
    timescale:
        build: timescale
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "pass"
        restart: always
        ports:
            - 5432:5432

    logger-server:
        build: logger
        command:
            - python3 -u server.py
        restart: always

    logger-dispatcher:
        build: logger
        command:
            - python3 -u dispatcher.py
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers
        restart: always
