version: "3"
services:
    timescale:
        build: timescale
        image: lumberjack-timescale
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "pass"
        restart: always
        ports:
            - 5432:5432

    lumberjack-server:
        build: lumberjack
        image: lumberjack
        command: "python3 -u server.py"
        restart: always

    lumberjack-dispatcher:
        build: lumberjack
        image: lumberjack
        command: "python3 -u dispatcher.py"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers
        restart: always
