version: "3"
services:
    timescale:
        build: timescale
        image: lumberjack-timescale
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "pass"
        restart: always
        ports:
            - 5432:5432

    lumberjack-server:
        build: server
        image: lumberjack-server
        restart: always

    lumberjack-dispatcher:
        build: dispatcher
        image: lumberjack-dispatcher
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers
        restart: always
