apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumberjack-server
  namespace: lumberjack
spec:
  selector:
    matchLabels:
      app: lumberjack-server
  #updateStrategy:
  #  type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: lumberjack-server
    spec:
      nodeSelector:
        lumberjack-test: "true"
      containers:
      - name: lumberjack-server
        image: lumberjack-server
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: lumberjack-server
  labels:
    app: lumberjack-server
spec:
  ports:
    - name: http
      port: 5000
  selector:
    app: lumberjack-server
