---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: timescale
  namespace: lumberjack
spec:
  selector:
    matchLabels:
      app: timescale
  template:
    metadata:
      labels:
        app: timescale
    spec:
      nodeSelector:
        lumberjack-db: "true"
      volumes:
        - name: timescale-volume
          hostPath:
            path: /srv/lumberjack-timescale
      containers:
        - name: timescale
          image: lumberjack-timescale
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pass
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescale-volume
---
apiVersion: v1
kind: Service
metadata:
  name: timescale
  namespace: lumberjack
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: timescale
